log_level: info
base_url: http://localhost:3000
#auth:
#  oidc:
#    client_id:
#    client_secret:
#    issuer_url:
#cors:
#  allow_origin:
session:
  lifetime: 86400 # 1 day
  cross_domain: false
#mdr:
#  endpoint:
