log_level: debug
base_url: http://localhost:3000
#auth:
#  oidc:
#    client_id:
#    client_secret:
#    auth_endpoint:
#    token_endpoint:
#    userinfo_endpoint:
#    session_lifetime:
#cors:
#  allow_origin:
#mdr:
#  endpoint:
