log_level: debug
base_url: http://localhost:3000
#auth:
#  oidc:
#    client_id:
#    client_secret:
#    issuer_url:
#cors:
#  allow_origin:
session:
  lifetime: 86400 # 15 days
  cross_domain: false
#mdr:
#  endpoint:
